CREATE TABLE game_results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  winner TEXT,
  gameConfig TEXT NOT NULL,
  logs TEXT NOT NULL,
  violationLogs TEXT NOT NULL,
  tokenLogs TEXT NOT NULL,
  p1Config TEXT NOT NULL,
  p2Config TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);